### PR TITLE
chore: update probot framework

### PR DESCRIPTION
**Pull request by Gabitchov**
- update probot
  - update jest
  - rewritten test with nock

### CODE REVIEW

**Comment by mithro** [comment]
Thanks for this!

It looks like CI is failing, do you think you would be able to fix that?

**Comment by Gabitchov** [comment]
Yes, let me check why it failed.

**Comment by Gabitchov** [comment]
For the continuous integration, I am quite confident but, for the deployment configuration, I am not sure where I can put the necessary update. I only changed the engine attribute in `package.json` to align with last versions.

**Comment by Gabitchov** [comment]
I think my PR could cover also the #54 one.

**Review by mithro — APPROVED** [review]
LGTM!

**Comment by mithro** [comment]
@Gabitchov - I updated the deployment of the bot but I'm getting the error shown on #60

**Pull request merged**
